const { normalizeStravaActivityDetail } = require("./stravaMapping.cjs");

class StravaDetailService {
  constructor({ client, tokenService, repository }) { Object.assign(this, { client, tokenService, repository }); this.pending = new Map(); }
  async getDetail(userId, activityId, force = false) { return this.deduplicate(`detail:${userId}:${activityId}`, async () => { const cached = await this.repository.getCache(userId, `detail:${activityId}`); if (cached && !force) return { ...cached, cached: true }; const token = await this.tokenService.getValidToken(userId); const detailResponse = await this.client.getActivity(token.accessToken, activityId); let zones = null; try { zones = (await this.client.getActivityZones(token.accessToken, activityId)).data; } catch (error) { if (error.status !== 404) throw error; } const detail = normalizeStravaActivityDetail(detailResponse.data, zones, new Date().toISOString()); if (!detail) throw Object.assign(new Error("Strava hat ungültige Aktivitätsdetails geliefert."), { statusCode: 502 }); await this.repository.setCache(userId, `detail:${activityId}`, detail); return { ...detail, cached: false }; }); }
  async getStreams(userId, activityId, types, force = false) { const selected = [...new Set(types)].sort(); return this.deduplicate(`streams:${userId}:${activityId}:${selected.join(",")}`, async () => { const cacheKey = `streams:${activityId}:${selected.join(",")}`; const cached = await this.repository.getCache(userId, cacheKey); if (cached && !force) return { streams: cached.streams, cachedAt: cached.cachedAt, cached: true }; const token = await this.tokenService.getValidToken(userId); let streams = {}; try { streams = (await this.client.getActivityStreams(token.accessToken, activityId, selected)).data || {}; } catch (error) { if (error.status !== 404) throw error; } const value = { streams, cachedAt: new Date().toISOString() }; await this.repository.setCache(userId, cacheKey, value); return { ...value, cached: false }; }); }
  deduplicate(key, operation) { if (this.pending.has(key)) return this.pending.get(key); const promise = operation().finally(() => this.pending.delete(key)); this.pending.set(key, promise); return promise; }
}

module.exports = { StravaDetailService };
