import Ionicons from "@expo/vector-icons/Ionicons";
import { Linking, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { colors, radius, spacing, typography } from "../theme";
import { formatActivityDistance, formatActivityDuration, getActivitySportLabel } from "../utils/activityAnalytics";

export function ActivityDetailModal({ activity, cache, error, visible, onClose, onLoad, onLoadStreams, onRefresh, matchingSessions = [], onMatch }) {
  if (!activity) return null;
  const detail = cache?.detail ?? activity;
  const facts = activityFacts(detail);
  return <Modal animationType="slide" presentationStyle="pageSheet" visible={visible} onRequestClose={onClose}><SafeAreaView style={styles.safeArea} edges={["top", "bottom"]}>
    <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Aktivitätsdetails schließen" onPress={onClose} style={styles.iconButton}><Ionicons name="close" size={24} color={colors.textPrimary} /></Pressable><Text style={styles.headerTitle}>Aktivitätsdetails</Text><Pressable accessibilityRole="button" accessibilityLabel="Aktivität aktualisieren" onPress={onRefresh} style={styles.iconButton}><Ionicons name="refresh" size={21} color={colors.textPrimary} /></Pressable></View>
    <ScrollView contentContainerStyle={styles.content}>
      <Text style={styles.eyebrow}>{getActivitySportLabel(detail.sport).toUpperCase()} · {detail.source || "Strava"}</Text><Text style={styles.title}>{detail.name}</Text>
      <Text style={styles.date}>{new Intl.DateTimeFormat("de-DE", { dateStyle: "long", timeStyle: "short" }).format(new Date(detail.startDateTime))}</Text>
      <View style={styles.facts}>{facts.map((fact) => <View key={fact.label} style={styles.fact}><Text style={styles.factValue}>{fact.value}</Text><Text style={styles.factLabel}>{fact.label}</Text></View>)}</View>
      {!cache?.detail ? <Action label="Detaildaten laden" onPress={onLoad} /> : null}
      {error ? <Text style={styles.error}>{error}</Text> : null}
      {detail.laps?.length ? <DetailList title="Runden" values={detail.laps} /> : null}
      {detail.splitsMetric?.length ? <DetailList title="Kilometer-Splits" values={detail.splitsMetric} /> : null}
      {detail.heartRateZones?.length ? <ZoneList title="Herzfrequenzzonen" values={detail.heartRateZones} /> : null}
      {detail.powerZones?.length ? <ZoneList title="Leistungszonen" values={detail.powerZones} /> : null}
      <View style={styles.section}><Text style={styles.sectionTitle}>Plan-Zuordnung</Text>{activity.plannedSessionId ? <Action label="Zuordnung aufheben" onPress={() => onMatch(null)} /> : matchingSessions.length ? matchingSessions.map((session) => <Action key={session.id} label={`Mit „${session.title}“ verknüpfen`} onPress={() => onMatch(session.id)} />) : <Text style={styles.description}>Keine passende geplante Einheit an diesem Tag vorhanden.</Text>}</View>
      {cache?.streams?.streams ? <StreamOverview streams={cache.streams.streams} /> : <Action label="Verläufe für Analyse laden" onPress={onLoadStreams} />}
      {detail.externalUrl ? <Action label="Auf Strava ansehen" onPress={() => Linking.openURL(detail.externalUrl)} /> : null}
      {cache?.cachedAt ? <Text style={styles.cache}>Lokal zwischengespeichert: {new Intl.DateTimeFormat("de-DE", { dateStyle: "short", timeStyle: "short" }).format(new Date(cache.cachedAt))}</Text> : null}
    </ScrollView>
  </SafeAreaView></Modal>;
}

function Action({ label, onPress }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({ pressed }) => [styles.action, pressed && styles.pressed]}><Text style={styles.actionText}>{label}</Text></Pressable>; }
function DetailList({ title, values }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{values.slice(0, 25).map((item, index) => <View key={`${title}-${index}`} style={styles.row}><Text style={styles.rowLabel}>{item.name || `${index + 1}`}</Text><Text style={styles.rowValue}>{[formatActivityDistance(item.distanceMeters), formatActivityDuration(item.movingTimeSeconds ?? item.elapsedTimeSeconds)].filter(Boolean).join(" · ")}</Text></View>)}</View>; }
function ZoneList({ title, values }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{values.map((item) => <View key={item.zone} style={styles.row}><Text style={styles.rowLabel}>Zone {item.zone}</Text><Text style={styles.rowValue}>{formatActivityDuration(item.timeSeconds)}</Text></View>)}</View>; }
function StreamOverview({ streams }) { const chartEntries = ["heartrate", "watts", "velocity_smooth", "altitude", "cadence"].filter((key) => Array.isArray(streams[key]?.data) && streams[key].data.length); return <View style={styles.section}><Text style={styles.sectionTitle}>Verläufe</Text>{chartEntries.length ? chartEntries.map((key) => <StreamChart key={key} label={streamLabel(key)} values={streams[key].data} />) : <Text style={styles.description}>Für diese Aktivität sind keine angeforderten Verläufe verfügbar.</Text>}</View>; }
function StreamChart({ label, values }) { const sampled = sample(values, 32); const numeric = sampled.filter(Number.isFinite); if (!numeric.length) return null; const min = Math.min(...numeric); const max = Math.max(...numeric); const range = Math.max(1, max - min); return <View style={styles.chart}><View style={styles.chartHeader}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{Math.round(min)}–{Math.round(max)}</Text></View><View style={styles.bars}>{sampled.map((value, index) => <View key={`${label}-${index}`} style={[styles.bar, { height: 6 + (Number.isFinite(value) ? (value - min) / range * 42 : 0) }]} />)}</View></View>; }
function sample(values, count) { if (values.length <= count) return values; return Array.from({ length: count }, (_, index) => values[Math.floor(index * (values.length - 1) / (count - 1))]); }
function activityFacts(activity) { const pace = activity.sport === "run" && activity.distanceMeters ? formatPace((activity.movingTimeSeconds ?? activity.durationSeconds) / (activity.distanceMeters / 1000), "min/km") : activity.sport === "swim" && activity.distanceMeters ? formatPace((activity.movingTimeSeconds ?? activity.durationSeconds) / (activity.distanceMeters / 100), "min/100 m") : null; const speed = activity.sport === "bike" && activity.averageSpeed ? `${(activity.averageSpeed * 3.6).toFixed(1)} km/h` : null; return [["Dauer", formatActivityDuration(activity.durationSeconds)], ["Bewegungszeit", formatActivityDuration(activity.movingTimeSeconds)], ["Distanz", formatActivityDistance(activity.distanceMeters)], ["Pace", pace], ["Geschwindigkeit", speed], ["Herzfrequenz", activity.averageHeartRate ? `${Math.round(activity.averageHeartRate)} bpm` : null], ["Leistung", activity.averagePower ? `${Math.round(activity.averagePower)} W` : null], ["Höhenmeter", activity.elevationGainMeters ? `${Math.round(activity.elevationGainMeters)} m` : null], ["Kalorien", activity.calories ? `${Math.round(activity.calories)} kcal` : null], ["Gerät", activity.deviceName]].filter(([, value]) => value).map(([label, value]) => ({ label, value })); }
function formatPace(seconds, unit) { return `${Math.floor(seconds / 60)}:${String(Math.round(seconds % 60)).padStart(2, "0")} ${unit}`; }
function streamLabel(key) { return { heartrate: "Herzfrequenz", watts: "Leistung", velocity_smooth: "Geschwindigkeit", altitude: "Höhe", cadence: "Kadenz", distance: "Distanz", time: "Zeit", grade_smooth: "Steigung", temp: "Temperatur" }[key] || key; }

const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: colors.background }, header: { minHeight: 56, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: spacing.md, borderBottomWidth: 1, borderColor: colors.border }, iconButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, headerTitle: { ...typography.caption, color: colors.textPrimary }, content: { padding: spacing.xl, paddingBottom: spacing.huge }, eyebrow: { ...typography.label, color: colors.textSecondary }, title: { ...typography.headline, marginTop: spacing.sm, color: colors.textPrimary }, date: { ...typography.caption, marginTop: spacing.sm, color: colors.textSecondary }, facts: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md, marginTop: spacing.xl }, fact: { width: "46%", flexGrow: 1, minHeight: 76, padding: spacing.md, borderRadius: radius.sm, backgroundColor: colors.surface }, factValue: { ...typography.title, color: colors.textPrimary }, factLabel: { fontSize: 11, lineHeight: 15, marginTop: spacing.xs, color: colors.textSecondary }, section: { marginTop: spacing.xxl }, sectionTitle: { ...typography.title, marginBottom: spacing.md, color: colors.textPrimary }, row: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md, borderBottomWidth: 1, borderColor: colors.border }, rowLabel: { ...typography.caption, color: colors.textPrimary }, rowValue: { ...typography.caption, color: colors.textSecondary }, description: { ...typography.caption, color: colors.textSecondary }, chart: { marginBottom: spacing.lg }, chartHeader: { flexDirection: "row", justifyContent: "space-between", marginBottom: spacing.sm }, bars: { height: 50, flexDirection: "row", alignItems: "flex-end", gap: 2, overflow: "hidden", borderBottomWidth: 1, borderColor: colors.border }, bar: { flex: 1, minWidth: 2, backgroundColor: colors.accent }, action: { minHeight: 48, alignItems: "center", justifyContent: "center", marginTop: spacing.lg, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, actionText: { ...typography.caption, color: colors.textPrimary }, error: { ...typography.caption, marginTop: spacing.md, color: colors.danger }, cache: { fontSize: 10, lineHeight: 14, marginTop: spacing.xl, color: colors.textMuted }, pressed: { opacity: 0.68 } });
